### ISSUE TITLE
When I write more than 1 letter hints hidden

### ISSUE THREAD

**Issue by canyavall** [mackenza/Brackets-PHP-SmartHints#31]
Here we can see that if I write only the first letter, I can see the hints:
![image](https://cloud.githubusercontent.com/assets/11173569/7270358/fb0469d2-e8db-11e4-96d7-56585d9f7727.png)

But, when i write the second letter:
![image](https://cloud.githubusercontent.com/assets/11173569/7270380/0f9bc9f8-e8dc-11e4-999c-8807a0d18e26.png)

It dissapears....

Maybe I miss something in the configuration!

**Comment by mackenza** [comment]
are you using the latest version? This looks like something I addressed in the last update.

**Comment by canyavall** [comment]
Yes, in theory, I'm using the extension manager for brackets so...., and I've just deleted it and installed again, and still the same problem... It was working properly some weeks ago but I can't remember when it started to fail...

**Comment by mackenza** [comment]
I seer the problem. I am trying to come up with a viable solution. It should be fixed in the next couple of days.

**Comment by canyavall** [comment]
Perfect, Thank you very much!

**Comment by mackenza** [comment]
not sure if this is 100% the right fix, but I think it's ok for now. Please test it out and see.

**Comment by canyavall** [comment]
hi mackenza, still have the same issue... if I can help you with something just tell me!

**Comment by mackenza** [comment]
@canyavall I cannot reproduce the issue using `1.1.7` that I published the other day.

If I look at your original screenshots, I am not seeing the bug as there is nothing in the drop down (that I can see, note that the screenshot cuts off the bottom) that starts with `$oT` so therefore there would be no more hints.

This works for me:
```php
$bbb = "";
$bbbb = "";
$bbbbb = "";
```
now if I start typing `$` I get a dropdown with all 3. If I continue typing `$bbb` I still get all 3. If I type `$bbbb` I get 2 and so on.

Can you please update me with what you are seeing that is not working?

**Comment by canyavall** [comment]
Well, now I was trying to reproduce the issue, and I couldn't... now I get the list, sometimes....

Here one issue, diferent, just it doesn't wshow me the variable:
![image](https://cloud.githubusercontent.com/assets/11173569/7610793/0589927e-f980-11e4-9d13-bd66e6f6f0ae.png)

Now is working sometimes:
![image](https://cloud.githubusercontent.com/assets/11173569/7610808/2162f85a-f980-11e4-9cc9-4290b76d9874.png)


But not always:
![image](https://cloud.githubusercontent.com/assets/11173569/7610819/2f15c324-f980-11e4-80fd-56921d8d15a1.png)

Maybe I should reinstall it? or all brackets?

**Comment by mackenza** [comment]
no, don't reinstall, it won't help.

Let me look at the above and see what I find.

**Comment by mackenza** [comment]
I think it's a case thing. Let me take a look and see what a good fix would be.

**Comment by mackenza** [comment]
I believe I have addressed the issues you were getting by making the hint match be case insensitive. Please test it out and open this again if I have not fixed it completely.
